#!/bin/tcsh

#setenv LD_LIBRARY_PATH /clhome/XPCS8/hdf5/hdf5-1.8.12-linux-x86_64-shared/lib
#setenv LD_LIBRARY_PATH {$LD_LIBRARY_PATH}:/clhome/XPCS8/hdf5/boost155Install/lib
#setenv HDF5_PLUGIN_PATH /clhome/XPCS8/hdf5/HDF5Plugin-master

/APSshare/epd/rh6-x86_64/bin/python h5ls.py "$1" 

